services:
- type: pserv
  name: odiopay-live-be-db-sandbox
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: odiopay-live-be-db-sandbox
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: odiopay-live-be-db-sandbox

envVarGroups:
- name: odiopay-live-be-db-sandbox
  envVars:
  - key: MYSQL_DATABASE
    value: odiopay-live-be-db-sandbox
  - key: MYSQL_USER
    value: odiopay-live-be-db-sandbox-user
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
